[16.0][MIG] product_configurator: Migration to 16.0
OCA/product-configurator pull request #101
Opened 2023-12-09 14:47 UTC by dreispt

- [REF] dotfiles: copier update
- Initial commit
- [ADD] Updated README files for repository
- [ADD] Added product_configurator_wizard to repository
- [ADD] Added i18n to modules
- [FIX] Calling _get_custom_vals on single record, typo fix
- [FIX] Fixed faulty path to assets view issue/2
- [FIX] Using single record instead of recordset
- [FIX] Backport from 10.0 branch - Remove variant search on binary custom field
- de translations of product_configurator (Pledra)
- [FIX] Formatting prices according to language in website
- [IMP] Removed unsafe literal_eval, offer flexiblity to make custom conversions, offering verbose error message on failure
- [ADD] Added app cover images
- [IMP] Added dp to formatLang calls when formatting prices
- [IMP] Tidy up views for custom values
- [IMP] Fix mutable default arguments
- [IMP] Computing prices using pricelists & breaking functionality across more methods to enhance code extensibility
- Merge pull request #28 from PCatinean/10.0
- Merge pull request #32 from PCatinean/10.0-fork
- [FIX] Sudo on attribute values related products for price calculation and image update
- Custom values from Wizard (#27)
- Flake8 fixes (#47)
- Removed price_extra field from attribute value from view
- [ENH] Enable usage of OR operators on domain lines
- [ENH] Hook for domain validataion.
- Create Variant Ids loop cleanup and test.
- Flake8 fixes
- [IMP/FIX] Preventing duplicates via checks and refactored create_variant to get_variant
- [FIX] Duplicate variant check Fix.
- seperate sale order form wizard module added new sale module for same level
- remove _wizard module and added defualt wizard to base module, creating variant on default action_config_done method
- defualt False explicitly and typo change
- create button will call the wizard to create new variant just from variant menu o configurator only
- move description of modules
- [FIX] Small fixes & flake8
- provide community support for form view and solve problem for the chain create button
- General fixes and flake8
- [IMP] Added default value with constrains on product.template
- [IMP] Implemented default values on configuration session level
- [IMP/FIX] Raising error message when modifying configuration restrictions, fixed empty default_val contraint check
- Overriding product search to prevent configurable products usage in standard Odoo modules
- Added mako template name generator, mrp routing on template and general fixes
- [FIX] General fixes
- Moved extra_lines_values to so wizard
- [FIX] Added config_ok to variant search
- New inheriting stock wizard, added facility for creating of lot from wizard only
- Renamed mako variables and newline trimmings for mako template name
- [WIP] Basic subconfiguration process
- Added bom routing and other fixes
- [WIP] onchange for attributes of regular subproducts
- Standard variant selection in configuration process with quantity
- [WIP] Adding quantities to attribute value related variants in wizard
- Added subconfigurable products to configuration wizard
- Storing prefixes in @property making general management easier
- Added configurator on mrp.production
- Added helper variables for mako template
- Fixed subconfiguration flow, quantities and boms
- General fixes and improvements
- Added bom to mako context and removed duplicate code outside try/except
- [FIX] Standard subproducts do not trigger subconfiguration
- Computing mako name only when template is not empty
- #T1532 initial commit for Migrate product_configurator module in odoo 11
- #T1532 partial commit
- Removed print statements from code
- Removed console.log, renamed __openerp__.py files to __manifest__.py
- Reverting changes for parts of code that reduce compatibility with standard Odoo
- Bumped version to 11.0 and removed all traces of coding: utf-8 from py files
- [MIG] Kept application only for base and website + fixed _get_price_extra
- [MIG] Fix default False for js framework reading persistent fields
- [FIX] Re-added functionality for no_save button action
- [FIX] Using no-save deepcopy of event to replicate same functionality, added sale_management instead of sale to configurator
- [FIX] Fixed default overriding existing values
- [FIX] value_ids readonly in wizard to preserve possible pre-existing session
- [FIX] Using new m2m field rendering with simple id list
- Disable view cache for backend wizard using context value to ensure dynamic view integrity (#146)
- [FIX] Updated data_manager load_views to new v11 syntax, switched attribute_line_ids from related to computed on product.configurator
- [FIX] Using new m2m frontend domains with simple field name instead of [0][2]
- Update README, replace iteritems->items, minor fixes
- [IMP][T0093] product_configurator: add product attributes and attribute values menu
- [IMP][T00401] product_configurator: Added General Setting Panel
- [FIX]product_configurator, website_product_configurator, product_configurator_mrp : correct method-name, claas-name, arguments
- [FIX]product_configurator : fix issue- error raises while copying configurable template and product attributes
- [FIX][T1902]product_configurator_stock : change js code to solve issue related to product-configuration on serial-number's form
- Moving config step related methods from product template to config session
- Moving all configuration related logic from product.template to config.session
- Fixed several navigation issues and bugs
- [IMP]product_configurator: Add action window for customized product attributes, add domain for custom values page visibility
- [IMP]product_configurator: Hide internal reference field and add image field back in product attribute
- Using config step name in view of sessions
- Creating new config.session for testcases, adapting to new design
- [FIX][T1902]product_configurator : make 'internal reference visible for ragular products, and hidden only on configurable products
- [FIX][T1902]product_configurator : clear progressive steps when go previous, variant price button on template, icon button on kanban tile for product configuration
- [FIX] fix flake8 error
- [FIX][T1902]product_configurator : active_cfg_line pass as arg in _clear_values_in_steps
- [T1902]product_configurator : remove function '_clear_values_in_steps'
- [T1902] hide internal ref from list view
- [T1902]product_configurator : remove extra code
- [T1902]product_configurator : move 'variant prices' button from hedder to smart button on variants
- [T1902]product_configurator: change location of variant prices button, change size of icon on kanban tile
- [T1902]product_configurator : remove first step from wizard if configuration starts from product
- [FIX][T1902]product_configurator : fix variant prices button
- [FIX][T1902]product_configurator : remove variable active_cfg_line
- [WIP][T1902]product_configurator: add test
- [FIX][T1902]product_configurator : add original attrs in product variant button
- [FIX][T1902]product_configurator : remove active_cfg_line
- [WIP][T1902]product_configurator: add test case for issue #59 and fix an bug while going to previous stage at time of configuring product
- [IMP]product_configurator: Add ir_sequence to product_config_sessions
- [IMP]product_configurator: Add reconfigure product button on variant form and kanban view
- [IMP]product_configurator: Set kanban view as default view for variants
- [IMP]product_configurator: Add reflection of custom and multi on attributes lines
- [FIX][T1902]product_configurator : fix flake8 error
- [IMP][T1902]product_configurator : add fa-lg on icon
- [FIX][T1902][new(039)]product_configurator,product_configurator_purchase,product_configurator_sale: call action_next_step to open next step directly
- [FIX][T1902]product_configurator,product_configurator_purchase,product_cnofigurator_sale: remove deletion of 'view_cache'from action and change icon
- [FIX][T1902]product_configurator,product_configurator_sale,product_configurator_purchase: add generic method and call that
- [FIX][T1902] : f [...]

2023-12-09 14:54 UTC, dreispt commented
@dannyadair This has the build fixed, and should be mergeable.
Does it make sense to go ahead with the merge? The original OR has no approvals.

Also, I am skeptical these modules will work on v16, because I understand that views are now cached after being generated the rst time. But I could be wrong.

2024-01-11 11:03 UTC, SirAionTech requested changes
Thanks for the PR!
I'm just now beginning to work on this module and looks great, I tried it and seems to be working good.
I have reviewed the code and suggested some changes in https://github.com/ursais/product-configurator/pull/3, let me know what you think.

Could you please squash bot commits as explained in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests? This PR already has a lot of commits.

I see there are also some edits due to https://github.com/OCA/product-configurator/pull/100, could you please remove them? A rebase on `16.0` might be enough since the PR has been merged.

For some reason the maintainer @PCatinean has not been tagged in the PR (doing it now), what do you think of this migration?

2024-01-11 11:03 UTC, SirAionTech commented on product_configurator/wizard/product_configurator.py
> +            "custom_field_prefix": "__custom_",
Just curious, why this change? This causes a lots of changes in the tests too

2024-01-21 05:54 UTC, dannyadair commented on product_configurator/wizard/product_configurator.py
> +            "custom_field_prefix": "__custom_",
I just took that from the original PR assuming there were Javascript changes that made that necessary

2024-01-21 10:16 UTC, dannyadair commented
Thank you @dreispt this actually works well, also @SirAionTech has great improvements would be great if this could be merged in with his suggested adjustments

2024-02-02 10:36 UTC, dreispt commented
@SirAionTech @dannyadair Proposed changes merged. If I get approval I can go ahead with the merge.

2024-02-02 10:48 UTC, dreispt commented
@Murtaza-OSI

2024-02-04 04:01 UTC, dannyadair approved these changes
Thank you @dreispt LGTM

2024-02-05 15:25 UTC, Murtaza-SerpentCS approved these changes

2024-02-05 15:28 UTC, dreispt commented
/ocabot merge nobump

2024-02-05 15:33 UTC, merged