[WIP]14.0 mig product configurator purchase
OCA/product-configurator pull request #31
Opened 2021-05-25 11:35 UTC by pledrateam

2021-05-28 16:59 UTC, patrickrwilson requested changes
Looks good, small changes requested and please add license info to py files.

2021-05-28 16:59 UTC, patrickrwilson commented on product_configurator_purchase/data/menu_product.xml
> +<?xml version="1.0" encoding="utf-8" ?>
This line is no longer needed (Since v11)

2021-05-28 16:59 UTC, patrickrwilson commented on product_configurator_purchase/demo/product_template.xml
> +<?xml version="1.0" encoding="utf-8" ?>
This line is no longer needed (Since v11)

2021-05-28 16:59 UTC, patrickrwilson commented on product_configurator_purchase/models/purchase.py
> +from odoo import api, fields, models
Please add missing license info at top.

2021-05-28 16:59 UTC, patrickrwilson commented on product_configurator_purchase/views/purchase_view.xml
> +<?xml version="1.0" ?>
This line is no longer needed (Since v11)

2021-05-28 16:59 UTC, patrickrwilson commented on product_configurator_purchase/wizard/product_configurator.py
> +from odoo import fields, models
Please add missing license info at top.

2021-06-11 08:11 UTC, PCatinean approved these changes

2021-06-11 13:58 UTC, patrickrwilson approved these changes
LGTM

2021-06-11 15:11 UTC, dreispt commented
/ocabot merge nobump

2021-06-15 12:55 UTC, PCatinean commented
@dreispt last issues should be fixed now

2021-06-15 12:56 UTC, PCatinean commented
/ocabot merge nobump

2021-06-15 13:52 UTC, dreispt commented
@PCatinean You my want to add your handle to the manifest `maintainers` key. Then the bot will accept you merge commands.

2021-06-15 13:52 UTC, dreispt commented
/ocabot merge nobump

2021-06-15 15:27 UTC, merged